import type { Lead360Item, LeadListGroup } from "./types";

export const initialLeadLists: LeadListGroup[] = [
  {
    id: "list-l1-sistema",
    name: "Leads Nivel 1 - Post SISTEMA",
    description: "Comentarios que pidieron la Guia en PDF en el post viral de Framework SISTEMA.",
    signalSource: "Post SISTEMA (Lead Magnet Propio)",
    signalLevel: "level_1",
    leadsCount: 28,
    assignedCampaign: "Secuencia Lead Magnet ManyChat (Nivel 1)",
    createdAt: "2026-10-05T09:00:00.000Z",
  },
  {
    id: "list-l1-plantilla",
    name: "Leads Nivel 1 - Post PLANTILLA",
    description: "Decisores que solicitaron la Plantilla de secuencias inbound.",
    signalSource: "Post PLANTILLA (Lead Magnet Propio)",
    signalLevel: "level_1",
    leadsCount: 54,
    assignedCampaign: "Secuencia Lead Magnet ManyChat (Nivel 1)",
    createdAt: "2026-10-06T14:30:00.000Z",
  },
  {
    id: "list-l2-adapta",
    name: "Leads Nivel 2 - Competencia Adapta IA",
    description: "Interacciones y comentarios en publicaciones de la competencia sobre automatizacion.",
    signalSource: "Competencia Adapta IA",
    signalLevel: "level_2",
    leadsCount: 42,
    assignedCampaign: "Secuencia Auditoria de Competencia",
    createdAt: "2026-10-04T11:00:00.000Z",
  },
  {
    id: "list-l3-pipeline",
    name: "Leads Nivel 3 - Tendencias Falta de Pipeline B2B",
    description: "Decisores calificados que debatieron en posts sobre generacion de pipeline en LinkedIn.",
    signalSource: "LinkedIn Global Keywords",
    signalLevel: "level_3",
    leadsCount: 88,
    assignedCampaign: "Secuencia Soft Outreach ICP",
    createdAt: "2026-10-03T16:00:00.000Z",
  },
];

export const initialLeadsData: Lead360Item[] = [
  {
    id: "lead-360-01",
    fullName: "Alejandro Ruiz",
    firstName: "Alejandro",
    lastName: "Ruiz",
    title: "Director Comercial",
    company: "ScaleTech Solutions",
    location: "Madrid, España",
    email: "aruiz@scaletech.es",
    phone: "+34 612 849 201",
    linkedinUrl: "https://www.linkedin.com/in/alejandro-ruiz-salestech",
    signalSource: "Post SISTEMA (Lead Magnet)",
    signalLevel: "level_1",
    intentScore: 95,
    stage: "active_conversation",
    sequenceStatus: "replied",
    listId: "list-l1-sistema",
    listName: "Leads Nivel 1 - Post SISTEMA",
    activeCampaignName: "Secuencia Lead Magnet ManyChat (Nivel 1)",
    createdAt: "2026-10-06T09:15:00.000Z",
    lastActivityAt: "Hace 15 minutos",
    timeline: [
      {
        id: "tl-1",
        timestamp: "Hace 2 dias a las 10:14 AM",
        title: "Señal Detectada (Nivel 1)",
        detail: 'Comentó "SISTEMA por favor, excelente contenido" en tu publicacion sobre prospeccion con IA.',
        type: "signal",
      },
      {
        id: "tl-2",
        timestamp: "Hace 2 dias a las 10:15 AM",
        title: "Paso A: Reaccion y Respuesta Publica",
        detail: 'Like al comentario y respuesta: "Te lo acabo de enviar por privado, revisa tus mensajes".',
        type: "dm",
      },
      {
        id: "tl-3",
        timestamp: "Hace 2 dias a las 10:18 AM",
        title: "Paso B: Entrega Instantanea por DM (Contacto 1er Grado)",
        detail: "Mensaje directo enviado con archivo adjunto: Guia_Framework_SISTEMA_InHubFlow.pdf.",
        type: "dm",
      },
      {
        id: "tl-4",
        timestamp: "Hace 15 minutos",
        title: "Respuesta del Prospecto en el Chat",
        detail: 'Alejandro respondio: "Muchas gracias por el PDF. ¿Como implementan el pacing de Unipile?". Secuencia pausada automaticamente.',
        type: "reply",
      },
      {
        id: "tl-5",
        timestamp: "Hace 14 minutos",
        title: "Actualizacion de Etapa CRM",
        detail: "Mover de 'Conectado / Material Entregado' a 'Conversacion Activa' en el Kanban.",
        type: "crm",
      },
    ],
  },
  {
    id: "lead-360-02",
    fullName: "Diego Vazquez",
    firstName: "Diego",
    lastName: "Vazquez",
    title: "CEO & Co-founder",
    company: "CloudFlow Labs",
    location: "Ciudad de Mexico, Mexico",
    email: "diego@cloudflowlabs.io",
    phone: "+52 55 4192 8820",
    linkedinUrl: "https://www.linkedin.com/in/diego-vazquez-cloud",
    signalSource: "Post SISTEMA (Lead Magnet)",
    signalLevel: "level_1",
    intentScore: 92,
    stage: "meeting_scheduled",
    sequenceStatus: "replied",
    listId: "list-l1-sistema",
    listName: "Leads Nivel 1 - Post SISTEMA",
    activeCampaignName: "Secuencia Lead Magnet ManyChat (Nivel 1)",
    createdAt: "2026-10-06T11:20:00.000Z",
    lastActivityAt: "Ayer a las 16:30",
    timeline: [
      {
        id: "tl-6",
        timestamp: "Hace 1 dia a las 11:20 AM",
        title: "Señal Detectada (Nivel 1)",
        detail: 'Comentó "SISTEMA" en la publicacion.',
        type: "signal",
      },
      {
        id: "tl-7",
        timestamp: "Hace 1 dia a las 11:22 AM",
        title: "Entrega de Material por DM",
        detail: "Envio de la guia en PDF.",
        type: "dm",
      },
      {
        id: "tl-8",
        timestamp: "Ayer a las 16:30",
        title: "Reunion Comercial Agendada",
        detail: "Agendada cita de demostracion de 30 min en el Calendario Integrado para este jueves.",
        type: "crm",
      },
    ],
  },
  {
    id: "lead-360-03",
    fullName: "Mariana Silva",
    firstName: "Mariana",
    lastName: "Silva",
    title: "Head of Marketing",
    company: "NovaB2B Agency",
    location: "Bogota, Colombia",
    email: "mariana.silva@novab2b.co",
    linkedinUrl: "https://www.linkedin.com/in/mariana-silva-marketing",
    signalSource: "Competencia: Adapta IA",
    signalLevel: "level_2",
    intentScore: 84,
    stage: "in_sequence",
    sequenceStatus: "in_progress",
    listId: "list-l2-adapta",
    listName: "Leads Nivel 2 - Competencia Adapta IA",
    activeCampaignName: "Secuencia Auditoria de Competencia",
    createdAt: "2026-10-06T15:00:00.000Z",
    lastActivityAt: "Ayer a las 15:10",
    timeline: [
      {
        id: "tl-9",
        timestamp: "Ayer a las 15:00",
        title: "Señal de Competencia Detectada (Nivel 2)",
        detail: "Interaccion en post de Adapta IA sobre agentes IA de prospeccion.",
        type: "signal",
      },
      {
        id: "tl-10",
        timestamp: "Ayer a las 15:05",
        title: "Visita de Perfil Ejecutada (Unipile)",
        detail: "Perfil visitado con exito para aparecer en sus notificaciones de LinkedIn.",
        type: "visit",
      },
      {
        id: "tl-11",
        timestamp: "Ayer a las 15:10",
        title: "Solicitud de Conexion Enviada",
        detail: "Invitacion con nota contextual enviada. En espera de aceptacion.",
        type: "invitation",
      },
    ],
  },
  {
    id: "lead-360-04",
    fullName: "Lucia Beltran",
    firstName: "Lucia",
    lastName: "Beltran",
    title: "Head of Revenue Operations",
    company: "FinTech Growth",
    location: "Bogota, Colombia",
    email: "lbeltran@fintechgrowth.co",
    linkedinUrl: "https://www.linkedin.com/in/lucia-beltran-revops",
    signalSource: "Post PLANTILLA (Lead Magnet)",
    signalLevel: "level_1",
    intentScore: 88,
    stage: "in_sequence",
    sequenceStatus: "in_progress",
    listId: "list-l1-plantilla",
    listName: "Leads Nivel 1 - Post PLANTILLA",
    activeCampaignName: "Secuencia Lead Magnet ManyChat (Nivel 1)",
    createdAt: "2026-10-07T08:00:00.000Z",
    lastActivityAt: "Hace 1 hora",
    timeline: [
      {
        id: "tl-12",
        timestamp: "Hace 1 hora",
        title: "Señal Detectada (Nivel 1)",
        detail: 'Comentó: "Quiero la PLANTILLA, muchas gracias".',
        type: "signal",
      },
      {
        id: "tl-13",
        timestamp: "Hace 58 minutos",
        title: "Solicitud de Conexion Enviada con Nota",
        detail: "Al no ser 1er grado, se envio invitacion contextual para entregar el recurso tras aceptacion.",
        type: "invitation",
      },
    ],
  },
  {
    id: "lead-360-05",
    fullName: "Guillermo Pardo",
    firstName: "Guillermo",
    lastName: "Pardo",
    title: "Managing Director",
    company: "Pardo & Partners",
    location: "Barcelona, España",
    email: "gpardo@pardopartners.com",
    linkedinUrl: "https://www.linkedin.com/in/guillermo-pardo-consulting",
    signalSource: "LinkedIn Global Keywords",
    signalLevel: "level_3",
    intentScore: 76,
    stage: "lead_captured",
    sequenceStatus: "paused",
    listId: "list-l3-pipeline",
    listName: "Leads Nivel 3 - Tendencias Falta de Pipeline B2B",
    activeCampaignName: "Secuencia Soft Outreach ICP",
    createdAt: "2026-10-07T07:30:00.000Z",
    lastActivityAt: "Hace 4 horas",
    timeline: [
      {
        id: "tl-14",
        timestamp: "Hace 4 horas",
        title: "Debate Global Detectado (Nivel 3)",
        detail: 'Participo en debate viral sobre tasas de respuesta B2B. Cumple criterios ICP: Cargo de Director en España.',
        type: "signal",
      },
    ],
  },
];
