import { ChatConversation } from "./types";

export const INITIAL_CONVERSATIONS: ChatConversation[] = [
  {
    id: "conv-1",
    leadId: "lead-1",
    leadName: "Alejandro Ruiz Gomez",
    leadTitle: "Director Comercial",
    company: "ScaleTech Solutions",
    location: "Madrid, Espana",
    avatarInitials: "AR",
    campaignSource: "Nivel 1 - Post Lead Magnet SISTEMA",
    leadMagnetUsed: "Guia_Pacing_LinkedIn_2026.pdf",
    crmStage: "Interesado",
    crmStageId: "interested",
    lastMessage: "Muchas gracias por el PDF. ¿Como implementan el pacing de Unipile?",
    lastMessageTime: "10:42 AM",
    unread: true,
    aiSuggestions: [
      "Utilizamos intervalos de jitter aleatorio de 3 a 12 minutos y limites diarios seguros para replicar el comportamiento humano.",
      "Con gusto podemos verlo en vivo. ¿Te viene bien una breve llamada de 15 minutos este jueves?",
      "Ademas del pacing, el sistema detecta automaticamente si respondes para pausar la secuencia al instante."
    ],
    messages: [
      {
        id: "msg-101",
        senderId: "user",
        senderName: "Roberto",
        isSender: true,
        text: "Hola Alejandro, un gusto saludarte. Vi tu comentario en mi publicacion sobre el sistema de automatizacion para LinkedIn. Aqui tienes la guia prometida:",
        timestamp: "09:30 AM",
        attachment: {
          name: "Guia_Pacing_LinkedIn_2026.pdf",
          type: "pdf",
          size: "2.4 MB",
        },
      },
      {
        id: "msg-102",
        senderId: "lead-1",
        senderName: "Alejandro Ruiz Gomez",
        isSender: false,
        text: "Muchas gracias por el PDF. Lo estuve hojeando y me parece muy acertado el enfoque. ¿Como implementan el pacing de Unipile para no levantar alarmas en las cuentas?",
        timestamp: "10:42 AM",
      },
    ],
  },
  {
    id: "conv-2",
    leadId: "lead-2",
    leadName: "Diego Vazquez",
    leadTitle: "CEO & Co-founder",
    company: "CloudFlow Labs",
    location: "Ciudad de Mexico, Mexico",
    avatarInitials: "DV",
    campaignSource: "Nivel 2 - Prospectos Adapta IA",
    leadMagnetUsed: "Playbook_Outbound_Social.pdf",
    crmStage: "Reunion Agendada",
    crmStageId: "meeting_scheduled",
    lastMessage: "Excelente, ya reserve en tu enlace de calendario para el viernes a las 11:00 AM.",
    lastMessageTime: "Ayer 17:15",
    unread: false,
    aiSuggestions: [
      "Perfecto Diego, ya tengo la reunion confirmada en Google Calendar. Te envio la orden del dia por correo.",
      "Excelente. Para aprovechar al maximo la sesion, ¿cuantos SDRs conforman actualmente tu equipo comercial?",
      "Quedo a tu disposicion si necesitas invitar a alguien mas de tu equipo directivo a la llamada."
    ],
    messages: [
      {
        id: "msg-201",
        senderId: "user",
        senderName: "Roberto",
        isSender: true,
        text: "Hola Diego, observe tu actividad en el sector cloud. Estamos implementando un flujo inbound para empresas con tu perfil. Te comparto el playbook:",
        timestamp: "Ayer 15:00",
        attachment: {
          name: "Playbook_Outbound_Social.pdf",
          type: "pdf",
          size: "4.1 MB",
        },
      },
      {
        id: "msg-202",
        senderId: "lead-2",
        senderName: "Diego Vazquez",
        isSender: false,
        text: "Hola Roberto. Muy buen material. Justo estamos buscando escalar la prospeccion B2B para Q4. ¿Podemos agendar una llamada breve esta semana?",
        timestamp: "Ayer 16:30",
      },
      {
        id: "msg-203",
        senderId: "user",
        senderName: "Roberto",
        isSender: true,
        text: "Por supuesto Diego. Puedes seleccionar el horario que mejor te convenga directamente aqui: https://cal.inhubflow.com/sdr-meeting",
        timestamp: "Ayer 16:45",
      },
      {
        id: "msg-204",
        senderId: "lead-2",
        senderName: "Diego Vazquez",
        isSender: false,
        text: "Excelente, ya reserve en tu enlace de calendario para el viernes a las 11:00 AM.",
        timestamp: "Ayer 17:15",
      },
    ],
  },
  {
    id: "conv-3",
    leadId: "lead-3",
    leadName: "Mariana Silva Castro",
    leadTitle: "Head of Demand Generation",
    company: "NovaB2B Marketing",
    location: "Bogota, Colombia",
    avatarInitials: "MS",
    campaignSource: "Nivel 3 - Social Selling Global",
    crmStage: "En Secuencia",
    crmStageId: "in_sequence",
    lastMessage: "Nota de voz recibida (0:48 seg)",
    lastMessageTime: "Ayer 12:20",
    unread: false,
    aiSuggestions: [
      "Entendido Mariana, escuche tu nota de voz. La integracion con HubSpot se hace en 2 clics via webhook.",
      "Totalmente de acuerdo en tu punto. Permiteme enviarte un video demostrativo de 2 minutos sobre esa funcion.",
      "¿Te pareceria bien agendar una videollamada de exploracion para ver el pipeline completo?"
    ],
    messages: [
      {
        id: "msg-301",
        senderId: "user",
        senderName: "Roberto",
        isSender: true,
        text: "Hola Mariana, me llamo mucho la atencion tu enfoque en captacion de demanda. Te dejo una breve nota de voz con contexto sobre nuestra plataforma:",
        timestamp: "Ayer 11:50",
        attachment: {
          name: "Nota_de_voz_introductoria.mp3",
          type: "audio",
          size: "0:35 seg",
        },
      },
      {
        id: "msg-302",
        senderId: "lead-3",
        senderName: "Mariana Silva Castro",
        isSender: false,
        text: "Hola Roberto, te respondo por audio para mayor agilidad:",
        timestamp: "Ayer 12:20",
        attachment: {
          name: "Respuesta_Mariana_HubSpot.mp3",
          type: "audio",
          size: "0:48 seg",
        },
      },
    ],
  },
  {
    id: "conv-4",
    leadId: "lead-4",
    leadName: "Carlos Mendez P.",
    leadTitle: "VP of Business Development",
    company: "Fintech Horizon",
    location: "Buenos Aires, Argentina",
    avatarInitials: "CM",
    campaignSource: "Nivel 1 - Post Lead Magnet SISTEMA",
    leadMagnetUsed: "Framework_Social_Selling_2026.pdf",
    crmStage: "Propuesta Presentada",
    crmStageId: "proposal_sent",
    lastMessage: "Revisamos los requerimientos tecnicos y estamos listos para la propuesta final.",
    lastMessageTime: "2 dias",
    unread: false,
    aiSuggestions: [
      "Excelente Carlos, te acabo de cargar la propuesta personalizada en el portal comercial.",
      "Perfecto. ¿Cuando proyectan tener la decision del comite directivo?",
      "¿Requieres que coordinemos una llamada con nuestro arquitecto de soluciones de Unipile?"
    ],
    messages: [
      {
        id: "msg-401",
        senderId: "lead-4",
        senderName: "Carlos Mendez P.",
        isSender: false,
        text: "Revisamos los requerimientos tecnicos con el equipo de TI y estamos listos para revisar la propuesta final con los planes Enterprise.",
        timestamp: "Hace 2 dias",
      },
    ],
  },
];
