import type {
  Level1Monitor,
  Level2CompetitorMonitor,
  Level3GlobalMonitor,
  SignalLeadItem,
} from "./types";

export const initialLevel1Monitors: Level1Monitor[] = [
  {
    id: "mon-l1-01",
    postTitle: "Framework de 4 pasos para prospeccion B2B con IA",
    postUrl: "https://www.linkedin.com/feed/update/urn:li:activity:718920194829102",
    keyword: "SISTEMA",
    status: "active",
    autoLikeComment: true,
    publicReplyTemplate: "Te lo acabo de enviar por privado, revisa tus mensajes",
    nonConnectedNoteTemplate:
      "Hola {{first_name}}, vi que comentaste 'SISTEMA' en mi post. Te envio la invitacion para poder entregarte la guia por mensaje privado. Saludos.",
    attachedPdfName: "Guia_Framework_SISTEMA_InHubFlow.pdf",
    scannedCommentsCount: 64,
    leadsCapturedCount: 28,
    lastScanAt: "Hace 12 minutos",
    createdAt: "2026-10-05T09:00:00.000Z",
  },
  {
    id: "mon-l1-02",
    postTitle: "Plantilla descargable de secuencias inbound para LinkedIn",
    postUrl: "https://www.linkedin.com/feed/update/urn:li:activity:718911029384912",
    keyword: "PLANTILLA",
    status: "active",
    autoLikeComment: true,
    publicReplyTemplate: "Enviado por privado, espero te sea de maximo provecho",
    nonConnectedNoteTemplate:
      "Hola {{first_name}}, te agrego para poder compartirte la plantilla que solicitaste en mi publicacion. Un saludo.",
    attachedPdfName: "Plantilla_Secuencias_Inbound_2026.pdf",
    scannedCommentsCount: 112,
    leadsCapturedCount: 54,
    lastScanAt: "Hace 45 minutos",
    createdAt: "2026-10-06T14:30:00.000Z",
  },
];

export const initialLevel2Monitors: Level2CompetitorMonitor[] = [
  {
    id: "mon-l2-01",
    competitorName: "Adapta IA / Perfil Corporativo",
    competitorUrl: "https://www.linkedin.com/company/adapta-ia",
    keywordsFilter: ["Agentes IA", "Prospeccion B2B", "Outbound"],
    status: "active",
    interactionTypes: ["comments", "likes"],
    outreachTemplate:
      "Hola {{first_name}}, vi tu interaccion en el post de Adapta IA sobre {{tema}}. Me parecio muy interesante tu punto de vista... ¿como lo estan abordando en {{company}}?",
    leadsIdentifiedCount: 42,
    lastScanAt: "Hace 28 minutos",
    createdAt: "2026-10-04T11:00:00.000Z",
  },
  {
    id: "mon-l2-02",
    competitorName: "GrowthLab B2B",
    competitorUrl: "https://www.linkedin.com/company/growthlab-b2b",
    keywordsFilter: ["Cold Email vs LinkedIn", "Pipeline"],
    status: "active",
    interactionTypes: ["comments"],
    outreachTemplate:
      "Hola {{first_name}}, vi que comentaste en el post de GrowthLab respecto al reto de generar pipeline. Te comparto un enfoque alternativo que nos ha funcionado...",
    leadsIdentifiedCount: 19,
    lastScanAt: "Hace 2 horas",
    createdAt: "2026-10-06T08:00:00.000Z",
  },
];

export const initialLevel3Monitors: Level3GlobalMonitor[] = [
  {
    id: "mon-l3-01",
    searchQuery: "Falta de pipeline B2B OR Prospeccion en frio",
    icpTitles: ["CEO", "Founder", "VP Sales", "Head of Growth", "Director Comercial"],
    locations: ["España", "Mexico", "Colombia", "Chile"],
    minPostReactions: 50,
    status: "active",
    leadsIdentifiedCount: 88,
    lastScanAt: "Hace 15 minutos",
    createdAt: "2026-10-03T16:00:00.000Z",
  },
  {
    id: "mon-l3-02",
    searchQuery: "Social Selling B2B OR Lead Magnets LinkedIn",
    icpTitles: ["Marketing Director", "Growth Lead", "Gerente de Ventas"],
    locations: ["España", "Latinoamerica"],
    minPostReactions: 40,
    status: "active",
    leadsIdentifiedCount: 65,
    lastScanAt: "Hace 1 hora",
    createdAt: "2026-10-05T12:00:00.000Z",
  },
];

export const initialDiscoveredLeads: SignalLeadItem[] = [
  {
    id: "s-lead-01",
    monitorId: "mon-l1-01",
    fullName: "Alejandro Ruiz",
    headline: "Director Comercial en ScaleTech Solutions",
    company: "ScaleTech Solutions",
    location: "Madrid, España",
    linkedinUrl: "https://www.linkedin.com/in/alejandro-ruiz-salestech",
    connectionDegree: "1st",
    intentLevel: "very_high",
    signalSnippet: 'Comentó: "SISTEMA por favor, excelente contenido"',
    detectedAt: "Hace 14 minutos",
    status: "dm_sent",
    attachedResource: "Guia_Framework_SISTEMA_InHubFlow.pdf",
  },
  {
    id: "s-lead-02",
    monitorId: "mon-l1-01",
    fullName: "Diego Vazquez",
    headline: "CEO & Co-founder en CloudFlow Labs",
    company: "CloudFlow Labs",
    location: "Ciudad de Mexico, Mexico",
    linkedinUrl: "https://www.linkedin.com/in/diego-vazquez-cloud",
    connectionDegree: "2nd",
    intentLevel: "very_high",
    signalSnippet: 'Comentó: "SISTEMA"',
    detectedAt: "Hace 35 minutos",
    status: "connected",
    attachedResource: "Guia_Framework_SISTEMA_InHubFlow.pdf",
  },
  {
    id: "s-lead-03",
    monitorId: "mon-l1-02",
    fullName: "Lucia Beltran",
    headline: "Head of Revenue Operations en FinTech Growth",
    company: "FinTech Growth",
    location: "Bogota, Colombia",
    linkedinUrl: "https://www.linkedin.com/in/lucia-beltran-revops",
    connectionDegree: "2nd",
    intentLevel: "very_high",
    signalSnippet: 'Comentó: "Quiero la PLANTILLA, muchas gracias"',
    detectedAt: "Hace 1 hora",
    status: "invitation_sent",
    attachedResource: "Plantilla_Secuencias_Inbound_2026.pdf",
  },
  {
    id: "s-lead-04",
    monitorId: "mon-l2-01",
    fullName: "Mariana Silva",
    headline: "Head of Marketing en NovaB2B Agency",
    company: "NovaB2B Agency",
    location: "Bogota, Colombia",
    linkedinUrl: "https://www.linkedin.com/in/mariana-silva-marketing",
    connectionDegree: "2nd",
    intentLevel: "medium_high",
    signalSnippet: 'Comentó en post de Adapta IA: "Coincido en que los SDRs sin IA estan perdiendo eficiencia"',
    detectedAt: "Hace 2 horas",
    status: "invitation_sent",
  },
  {
    id: "s-lead-05",
    monitorId: "mon-l2-01",
    fullName: "Javier Mendoza",
    headline: "VP of Enterprise Sales en Global Soft",
    company: "Global Soft",
    location: "Santiago, Chile",
    linkedinUrl: "https://www.linkedin.com/in/javier-mendoza-sales",
    connectionDegree: "3rd",
    intentLevel: "medium_high",
    signalSnippet: "Reaccionó con Insightful en publicacion sobre automatizacion de outreach",
    detectedAt: "Hace 3 horas",
    status: "new",
  },
  {
    id: "s-lead-06",
    monitorId: "mon-l3-01",
    fullName: "Guillermo Pardo",
    headline: "Managing Director en Pardo & Partners Consultoria",
    company: "Pardo & Partners",
    location: "Barcelona, España",
    linkedinUrl: "https://www.linkedin.com/in/guillermo-pardo-consulting",
    connectionDegree: "2nd",
    intentLevel: "medium",
    signalSnippet: 'Comentó en debate viral: "El mayor cuello de botella en 2026 es el ratio de respuesta en frio"',
    detectedAt: "Hace 4 horas",
    status: "new",
  },
];
