import { CommercialMeeting, PipelineDeal, PipelineStageConfig } from "./types";

export const PIPELINE_STAGES: PipelineStageConfig[] = [
  {
    id: "lead_captured",
    name: "1. Lead Captado",
    order: 1,
    badgeColor: "bg-gray-100 text-gray-700 dark:bg-gray-800 dark:text-gray-300",
    headerBorder: "border-t-gray-400",
  },
  {
    id: "in_sequence",
    name: "2. En Secuencia",
    order: 2,
    badgeColor: "bg-blue-50 text-blue-700 dark:bg-blue-950/40 dark:text-blue-300",
    headerBorder: "border-t-blue-500",
  },
  {
    id: "connected_material_sent",
    name: "3. Conectado / Material",
    order: 3,
    badgeColor: "bg-cyan-50 text-cyan-700 dark:bg-cyan-950/40 dark:text-cyan-300",
    headerBorder: "border-t-cyan-500",
  },
  {
    id: "interested",
    name: "4. Conversacion / Interesado",
    order: 4,
    badgeColor: "bg-brand-50 text-brand-700 dark:bg-brand-950/40 dark:text-brand-300",
    headerBorder: "border-t-brand-500",
  },
  {
    id: "meeting_scheduled",
    name: "5. Reunion Agendada",
    order: 5,
    badgeColor: "bg-purple-50 text-purple-700 dark:bg-purple-950/40 dark:text-purple-300",
    headerBorder: "border-t-purple-500",
  },
  {
    id: "proposal_sent",
    name: "6. Propuesta Presentada",
    order: 6,
    badgeColor: "bg-amber-50 text-amber-700 dark:bg-amber-950/40 dark:text-amber-300",
    headerBorder: "border-t-amber-500",
  },
  {
    id: "closed_won",
    name: "7. Ganado (Closed Won)",
    order: 7,
    badgeColor: "bg-emerald-50 text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-300",
    headerBorder: "border-t-emerald-500",
  },
];

export const INITIAL_DEALS: PipelineDeal[] = [
  {
    id: "deal-1",
    leadId: "lead-101",
    leadName: "Fernando Alva",
    leadTitle: "Director de Crecimiento",
    company: "SaaS Rocket",
    location: "Lima, Peru",
    avatarInitials: "FA",
    dealValue: "$1,200/mes",
    stageId: "lead_captured",
    sourceCampaign: "Nivel 1 - Post Lead Magnet SISTEMA",
    leadMagnetUsed: "Guia_Pacing_LinkedIn_2026.pdf",
    lastActivity: "Comentario escaneado en LinkedIn",
    nextAction: "Ejecutar auto-like y visita de perfil",
    priority: "Media",
  },
  {
    id: "deal-2",
    leadId: "lead-102",
    leadName: "Valeria Rios",
    leadTitle: "Gerente de Ventas B2B",
    company: "InnovaCorp",
    location: "Santiago, Chile",
    avatarInitials: "VR",
    dealValue: "$950/mes",
    stageId: "in_sequence",
    sourceCampaign: "Nivel 2 - Prospectos Adapta IA",
    lastActivity: "Invitacion de conexion enviada",
    nextAction: "Esperando aceptacion de red (Max 5 dias)",
    priority: "Alta",
  },
  {
    id: "deal-3",
    leadId: "lead-3",
    leadName: "Mariana Silva Castro",
    leadTitle: "Head of Demand Generation",
    company: "NovaB2B Marketing",
    location: "Bogota, Colombia",
    avatarInitials: "MS",
    dealValue: "$1,800/mes",
    stageId: "connected_material_sent",
    sourceCampaign: "Nivel 3 - Social Selling Global",
    leadMagnetUsed: "Playbook_Outbound_Social.pdf",
    lastActivity: "DM con recurso enviado y aceptado",
    nextAction: "Esperar ventana de 48h para follow-up",
    priority: "Media",
  },
  {
    id: "deal-4",
    leadId: "lead-1",
    leadName: "Alejandro Ruiz Gomez",
    leadTitle: "Director Comercial",
    company: "ScaleTech Solutions",
    location: "Madrid, Espana",
    avatarInitials: "AR",
    dealValue: "$2,400/mes",
    stageId: "interested",
    sourceCampaign: "Nivel 1 - Post Lead Magnet SISTEMA",
    leadMagnetUsed: "Guia_Pacing_LinkedIn_2026.pdf",
    lastActivity: "Respondio al DM consultando por Unipile",
    nextAction: "Enviar enlace de agendamiento SDR",
    priority: "Alta",
  },
  {
    id: "deal-5",
    leadId: "lead-2",
    leadName: "Diego Vazquez",
    leadTitle: "CEO & Co-founder",
    company: "CloudFlow Labs",
    location: "Ciudad de Mexico, Mexico",
    avatarInitials: "DV",
    dealValue: "$3,000/mes",
    stageId: "meeting_scheduled",
    sourceCampaign: "Nivel 2 - Prospectos Adapta IA",
    leadMagnetUsed: "Playbook_Outbound_Social.pdf",
    lastActivity: "Agendo cita por Cal.com para el viernes",
    nextAction: "Preparar demo tecnica y deck comercial",
    priority: "Alta",
    meetingDate: "Viernes, 11:00 AM",
  },
  {
    id: "deal-6",
    leadId: "lead-4",
    leadName: "Carlos Mendez P.",
    leadTitle: "VP of Business Development",
    company: "Fintech Horizon",
    location: "Buenos Aires, Argentina",
    avatarInitials: "CM",
    dealValue: "$4,500/mes",
    stageId: "proposal_sent",
    sourceCampaign: "Nivel 1 - Post Lead Magnet SISTEMA",
    leadMagnetUsed: "Framework_Social_Selling_2026.pdf",
    lastActivity: "Propuesta formal enviada al comite",
    nextAction: "Llamada de seguimiento contractual",
    priority: "Alta",
  },
  {
    id: "deal-7",
    leadId: "lead-105",
    leadName: "Andres Gutierrez",
    leadTitle: "Founder & Managing Director",
    company: "Apex Sales Advisory",
    location: "Medellin, Colombia",
    avatarInitials: "AG",
    dealValue: "$2,200/mes",
    stageId: "closed_won",
    sourceCampaign: "Nivel 3 - Social Selling Global",
    leadMagnetUsed: "Playbook_Outbound_Social.pdf",
    lastActivity: "Contrato firmado y onboarding iniciado",
    nextAction: "Conectar cuentas de LinkedIn en Unipile",
    priority: "Alta",
  },
];

export const INITIAL_MEETINGS: CommercialMeeting[] = [
  {
    id: "meet-1",
    leadName: "Diego Vazquez",
    company: "CloudFlow Labs",
    title: "Demostracion Tecnica InHubFlow + Unipile Pacing",
    date: "Viernes, 10 de Octubre",
    time: "11:00 AM - 11:45 AM",
    duration: "45 min",
    provider: "Google Calendar",
    meetingLink: "https://meet.google.com/inh-flow-demo",
    status: "Confirmada",
    timeZone: "America/Mexico_City (GMT-6)",
    attendees: ["roberto@inhubflow.com", "diego@cloudflowlabs.io"],
    dealValue: "$3,000/mes",
    notes: "Interesado en secuencias de Lead Magnet y proteccion antiban en la nube para 5 SDRs.",
  },
  {
    id: "meet-2",
    leadName: "Alejandro Ruiz Gomez",
    company: "ScaleTech Solutions",
    title: "Sesion de Exploracion & Arquitectura de Campanas",
    date: "Lunes, 13 de Octubre",
    time: "04:00 PM - 04:30 PM",
    duration: "30 min",
    provider: "Cal.com",
    meetingLink: "https://cal.inhubflow.com/room/sdr-alex",
    status: "Confirmada",
    timeZone: "Europe/Madrid (GMT+1)",
    attendees: ["roberto@inhubflow.com", "aruiz@scaletech.es"],
    dealValue: "$2,400/mes",
    notes: "Llego mediante el Lead Magnet SISTEMA. Busca automatizar follow-ups en LinkedIn.",
  },
  {
    id: "meet-3",
    leadName: "Elena Morales",
    company: "OutboundLab Agency",
    title: "Presentacion de Oferta Comercial & Licenciamiento",
    date: "Martes, 14 de Octubre",
    time: "03:30 PM - 04:15 PM",
    duration: "45 min",
    provider: "Outlook",
    meetingLink: "https://teams.microsoft.com/l/meetup-join/inhubflow",
    status: "Confirmada",
    timeZone: "America/Bogota (GMT-5)",
    attendees: ["roberto@inhubflow.com", "elena@outboundlab.co"],
    dealValue: "$1,800/mes",
    notes: "Revision de propuesta de marca blanca y dashboard para sus clientes B2B.",
  },
];
