import type { Edge, Node } from "@xyflow/react";
import type { NodeConfigData } from "./types";

export const defaultCampaignNodes: Node[] = [
  {
    id: "node-tr-01",
    type: "triggerNode",
    position: { x: 340, y: 30 },
    data: {
      label: "TR-01: Signal Monitor Trigger",
      category: "trigger",
      nodeType: "trigger_signal",
      description: "Escucha Monitor Nivel 1 (Palabra clave: SISTEMA)",
      signalLevel: "level_1",
      keyword: "SISTEMA",
    } as NodeConfigData,
  },
  {
    id: "node-ac-01",
    type: "actionNode",
    position: { x: 340, y: 170 },
    data: {
      label: "AC-01: Visitar Perfil",
      category: "action",
      nodeType: "action_visit",
      description: "Ejecuta visita mediante Unipile para figurar en notificaciones",
    } as NodeConfigData,
  },
  {
    id: "node-cond-01",
    type: "conditionNode",
    position: { x: 330, y: 310 },
    data: {
      label: "LG-02: ¿Es Contacto de 1er Grado?",
      category: "logic",
      nodeType: "logic_condition",
      description: "Valida si ya existe conexion activa en LinkedIn",
      conditionType: "is_1st_degree",
    } as NodeConfigData,
  },
  {
    id: "node-ac-04",
    type: "actionNode",
    position: { x: 100, y: 480 },
    data: {
      label: "AC-04: Enviar Invitacion con Nota",
      category: "action",
      nodeType: "action_invite",
      description: "Nota: Hola {{first_name}}, vi tu comentario en mi post...",
      hasNote: true,
      noteText: "Hola {{first_name}}, te envio invitacion para compartirte la guia por privado.",
    } as NodeConfigData,
  },
  {
    id: "node-delay-01",
    type: "delayNode",
    position: { x: 110, y: 620 },
    data: {
      label: "LG-01: Delay Esperar Aceptacion",
      category: "logic",
      nodeType: "logic_delay",
      description: "Espera hasta 3 dias en horario laboral (09:00 - 18:00)",
      delayDays: 3,
      workingHoursOnly: true,
    } as NodeConfigData,
  },
  {
    id: "node-cond-02",
    type: "conditionNode",
    position: { x: 100, y: 760 },
    data: {
      label: "LG-02: ¿Acepto la Invitacion?",
      category: "logic",
      nodeType: "logic_condition",
      description: "Verifica si el decisor aprobo la conexion",
      conditionType: "accepted_invite",
    } as NodeConfigData,
  },
  {
    id: "node-ac-05",
    type: "actionNode",
    position: { x: 580, y: 480 },
    data: {
      label: "AC-05: Enviar DM + Adjuntar PDF",
      category: "action",
      nodeType: "action_dm",
      description: "Entrega directa del Lead Magnet con archivo adjunto",
      dmText: "Hola {{first_name}}, aqui tienes la guia en PDF que solicitaste.",
      attachedResource: "Guia_Framework_SISTEMA_InHubFlow.pdf",
    } as NodeConfigData,
  },
  {
    id: "node-delay-02",
    type: "delayNode",
    position: { x: 590, y: 630 },
    data: {
      label: "LG-01: Delay 48 Horas",
      category: "logic",
      nodeType: "logic_delay",
      description: "Pausa de seguimiento antes de evaluar respuesta",
      delayHours: 48,
      workingHoursOnly: true,
    } as NodeConfigData,
  },
  {
    id: "node-cond-03",
    type: "conditionNode",
    position: { x: 575, y: 770 },
    data: {
      label: "LG-02: ¿Respondio al DM?",
      category: "logic",
      nodeType: "logic_condition",
      description: "Deteccion automatica de interaccion en el chat",
      conditionType: "replied_to_dm",
    } as NodeConfigData,
  },
  {
    id: "node-crm-01",
    type: "crmNode",
    position: { x: 740, y: 940 },
    data: {
      label: "CR-01: Mover a 'Conversacion Activa'",
      category: "crm",
      nodeType: "crm_stage",
      description: "Detener secuencia y transferir al Inbox / Kanban",
      crmStageTarget: "s4",
    } as NodeConfigData,
  },
  {
    id: "node-ac-06",
    type: "actionNode",
    position: { x: 440, y: 940 },
    data: {
      label: "AC-05: Enviar Follow-up de Valor",
      category: "action",
      nodeType: "action_dm",
      description: "Seguimiento consultivo sin sonar insistente",
      dmText: "¿Pudiste revisar el framework {{first_name}}? Te comparto un caso practico...",
    } as NodeConfigData,
  },
];

export const defaultCampaignEdges: Edge[] = [
  { id: "e-tr-ac1", source: "node-tr-01", target: "node-ac-01", animated: true },
  { id: "e-ac1-cond1", source: "node-ac-01", target: "node-cond-01" },
  { id: "e-cond1-no", source: "node-cond-01", sourceHandle: "no", target: "node-ac-04", label: "NO" },
  { id: "e-cond1-yes", source: "node-cond-01", sourceHandle: "yes", target: "node-ac-05", label: "SI" },
  { id: "e-ac4-delay1", source: "node-ac-04", target: "node-delay-01" },
  { id: "e-delay1-cond2", source: "node-delay-01", target: "node-cond-02" },
  { id: "e-cond2-yes", source: "node-cond-02", sourceHandle: "yes", target: "node-ac-05", label: "SI" },
  { id: "e-ac5-delay2", source: "node-ac-05", target: "node-delay-02" },
  { id: "e-delay2-cond3", source: "node-delay-02", target: "node-cond-03" },
  { id: "e-cond3-yes", source: "node-cond-03", sourceHandle: "yes", target: "node-crm-01", label: "SI (Respondio)" },
  { id: "e-cond3-no", source: "node-cond-03", sourceHandle: "no", target: "node-ac-06", label: "NO (Sin respuesta)" },
];

export const availablePaletteNodes = [
  {
    type: "actionNode",
    label: "AC-01: Visitar Perfil",
    category: "action" as const,
    nodeType: "action_visit" as const,
    description: "Visita el perfil de LinkedIn para figurar en sus notificaciones",
  },
  {
    type: "actionNode",
    label: "AC-02: Like a Ultimo Post",
    category: "action" as const,
    nodeType: "action_like" as const,
    description: "Reacciona positivamente a la publicacion mas reciente",
  },
  {
    type: "actionNode",
    label: "AC-03: Comentar con IA",
    category: "action" as const,
    nodeType: "action_comment" as const,
    description: "Deja un comentario contextual y positivo en su post",
  },
  {
    type: "actionNode",
    label: "AC-04: Enviar Invitacion",
    category: "action" as const,
    nodeType: "action_invite" as const,
    description: "Solicita conexion con nota personalizada opcional",
  },
  {
    type: "actionNode",
    label: "AC-05: Enviar DM + Adjunto",
    category: "action" as const,
    nodeType: "action_dm" as const,
    description: "Envia mensaje directo con documento PDF o enlace",
  },
  {
    type: "actionNode",
    label: "AC-06: InMail Sales Nav",
    category: "action" as const,
    nodeType: "action_inmail" as const,
    description: "Envia InMail a prospectos fuera de red",
  },
  {
    type: "delayNode",
    label: "LG-01: Delay / Retardo",
    category: "logic" as const,
    nodeType: "logic_delay" as const,
    description: "Pausa en dias u horas con ventana de horario laboral",
  },
  {
    type: "conditionNode",
    label: "LG-02: Condicion Logica",
    category: "logic" as const,
    nodeType: "logic_condition" as const,
    description: "Bifurca el flujo segun conexion o respuesta",
  },
  {
    type: "crmNode",
    label: "CR-01: Mover Etapa CRM",
    category: "crm" as const,
    nodeType: "crm_stage" as const,
    description: "Mueve la tarjeta del prospecto en el Kanban comercial",
  },
  {
    type: "controlNode",
    label: "CT-01: Finalizar Flujo",
    category: "control" as const,
    nodeType: "control_end" as const,
    description: "Concluye la secuencia para este prospecto",
  },
];
